clean:
	rm -rf processors/db processors/incremental_db processors/quartus processors/work
	rm -f processors/*.rpt processors/*.summary processors/*.smsg processors/*.done processors/*.jdi processors/*.pin processors/*.pof processors/*.sof processors/*.sld processors/*.qws processors/*.jditmp
